### ISSUE TITLE
glibc might be a needed dependency

### ISSUE THREAD

**Issue by CrocoDuckoDucks** [lucianodato/speech-denoiser#1]
Hi there!

Amazing software here! While preparing an Arch Linux PKGBUILD I found this by running namcap on the end result:

```
$ namcap speech-denoiser-git-r33.24fe9f4-1-x86_64.pkg.tar.xz 
speech-denoiser-git E: Dependency glibc detected and not included (libraries ['usr/lib/libc.so.6', 'usr/lib/libm.so.6'] needed in files ['usr/lib/lv2/sdenoise.lv2/sdenoise.so'])
```
Maybe worth to check if glibc is a required dependency and, if so, update README.md likewise.

**Comment by lucianodato** [comment]
I will update the readme ASAP. Thanks for the suggestion.
