### ISSUE TITLE
tag for release

### ISSUE THREAD

**Issue by dvzrv** [lucianodato/speech-denoiser#10]
Hey there!

really nice plugin. I'd like to move it to the Arch Linux [community] repository. For that to happen you'll need to release a first version of it though!

Please keep in mind, that you have a submodule in your code (consider using [git subtree](https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging) instead), that will turn out to be just an empty folder, once you do a git tag for this project (as github sadly doesn't do this).

**Comment by lucianodato** [comment]
You are completely right. The thing is that i haven't had much time lately. I'm with a new job in a new city and that has been keeping me busy for a while. I will do what you asked as soon as I can.

**Comment by dvzrv** [comment]
Hehe, hey, that sounds like my life recently! ;-)
Thanks! Looking forward to a release! :)

**Comment by lucianodato** [comment]
This week I will work on the subtree thing and if testing goes well I will do a release

**Comment by lucianodato** [comment]
Ok, I did the subtree thing but I can't release now that GregorR chimed in. I will wait what comes out of his contribution for Xiph's Rnnoise lib. As soon as that's done I will.

**Comment by dvzrv** [comment]
Thanks for doing that. Hm, but as #11 seems to be more of a major rework, wouldn't it be good to first make a release?
