### ISSUE TITLE
Git Submodules?

### ISSUE THREAD

**Issue by CrocoDuckoDucks** [lucianodato/speech-denoiser#2]
Hi!
While lurking around in the code I had a look at static_rnnoise.sh. I see that you clone rnnoise there. I was just wondering whether you considered using a [Git Submodule](https://blog.github.com/2016-02-01-working-with-submodules/) instead. Just a thought.

**Comment by lucianodato** [comment]
I was considering this option but I didn't had the time yet to look into it. Makes sense completely.

**Comment by lucianodato** [comment]
Thanks for your collaboration. I consider this done now.

**Comment by dvzrv** [comment]
sorry to necrobump: you'll need to manually include the submodule in a release tarball, as github won't do that.
Another way of achieving the same is using [git subtree merging](https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging).
