### ISSUE TITLE
cant install, I believe i got all the requirements 

### ISSUE THREAD

**Issue by yurgburg** [lucianodato/speech-denoiser#20]
`ldf@ldf-MS-7B79:~/speech-denoiser$ chmod +x install.sh && ./install.sh
You are on a Linux system. Building for Linux
Updating build configuration files for rnnoise, please wait....
./autogen.sh: 10: autoreconf: not found
mv: cannot stat '../ltmain.sh': No such file or directory
./install.sh: line 24: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
The Meson build system
Version: 0.53.2
Source dir: /home/ldf/speech-denoiser
Build dir: /home/ldf/speech-denoiser/build
Build type: native build
Project name: speech-denoiser
Project version: undefined
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:13:0: ERROR: C library 'rnnoise-nu' not found

A full log can be found at /home/ldf/speech-denoiser/build/meson-logs/meson-log.txt
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory` installed everything and i got this error? Am I still missing something?

**Comment by trebmuh** [comment]
> Am I still missing something?

Seems you're missing:

`autoreconf: not found`

**Comment by yurgburg** [comment]
Oh, I thought I already got that well now I am getting a different error, I appreciate the help I just got ubuntu today.
`ldf@ldf-MS-7B79:~/speech-denoiser$ chmod +x install.sh && ./install.sh
You are on a Linux system. Building for Linux
Updating build configuration files for rnnoise, please wait....
configure.ac:8: installing 'scripts/compile'
configure.ac:13: installing 'scripts/install-sh'
configure.ac:13: installing 'scripts/missing'
Makefile.am:9: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:9:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:9:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:9:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:9:   its definition is in aclocal's search path.
Makefile.am: installing 'scripts/depcomp'
autoreconf: automake failed with exit status: 1
mv: cannot stat '../ltmain.sh': No such file or directory
configure: WARNING: unrecognized options: --disable-shared, --enable-static
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for a BSD-compatible install... /usr/bin/install -c
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for inline... inline
./configure: line 4436: LT_INIT: command not found
checking whether make supports nested variables... (cached) yes
./configure: line 4532: LT_LIB_M: command not found
checking for gcc way to treat warnings as errors... -Werror
checking if gcc supports __attribute__(( visibility("default") ))... yes
checking if gcc supports -fvisibility=hidden... yes
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'
make: *** No targets specified and no makefile found.  Stop.
The Meson build system
Version: 0.53.2
Source dir: /home/ldf/speech-denoiser
Build dir: /home/ldf/speech-denoiser/build
Build type: native build
Project name: speech-denoiser
Project version: undefined
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:13:0: ERROR: C library 'rnnoise-nu' not found

A full log can be found at /home/ldf/speech-denoiser/build/meson-logs/meson-log.txt
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory
`
