### ISSUE TITLE
Use less CPU when soft-bypassing

### ISSUE THREAD

**Issue by FrnchFrgg** [lucianodato/speech-denoiser#4]
Currently, soft-bypassing only sets the wet factor to 0, still performing the same denoising work. Since RNNoise is kind of expensive (my computer cannot run it reliably at 64 frames/period, it uses more than 90% dsp), bypassing it should disable the noise computations (maybe still keeping the buffer full to be able to feed RNNoise as soon as the wet_dry variable is > 0).

A workaround currently is to remove completely the plugin, which is usable because it has no parameter (yet?).

**Comment by lucianodato** [comment]
Right. That's an easy fix. I will fix it ASAP. Unfortunately rnnoise api is not yet finished so I can't provide any parameter to configure.

**Comment by lucianodato** [comment]
Should be good now. Feel free to close it if is good in your system.

**Comment by lucianodato** [comment]
I believe that this is now fixed. Tested with my system only. If this doesn't work in yours please reopen it.
