### ISSUE TITLE
.so library

### ISSUE THREAD

**Issue by zhly0** [lucianodato/speech-denoiser#5]
Thanks for your work,is it possible to provide a so library with a .h file?not just a plugin?Thanks

**Comment by lucianodato** [comment]
Are you still interested in getting the binary of the plugin? I saw your discussions with Jean-Marc so I guess you had already tried out the rnnoise library. If you don't feel free to close the issue.

**Comment by zhly0** [comment]
Yes,I get the library of rnnoise,how could I get the library of your denoise code:noise-repellent?
Thanks!

**Comment by lucianodato** [comment]
I don't provide binaries for now but it's quite easy to compile. Download the repo and cd into it. Then do something like this if you are in linux
  chmod +x static_rnnoise.sh
  ./static_rnnoise.sh
  meson build --buildtype release --prefix "/usr/local/lib/lv2" && cd build
  ninja && sudo ninja install
Make sure to have the dependencies required installed.
