### ISSUE TITLE
Provide a wet/dry control

### ISSUE THREAD

**Issue by FrnchFrgg** [lucianodato/speech-denoiser#6]
Since rrnoise API is still in flux and you cannot provide meaningful controls for the plugin, maybe you can add a wet/dry control so that one can make the noise removal less strong (in some cases, the start of some F or S are removed a bit too much by rrnoise).

In the code you already use a wet/dry value for soft bypass anyway, so it should be very simple to do.

**Comment by FrnchFrgg** [comment]
One can of courseworkaround the problem with clever Pin Connections and some plugins like stereo balance (to delay the dry signal the same amount than Speech-denoiser does) and stereo crossfade to merge back the sounds, but that is very clunky.

**Comment by lucianodato** [comment]
I've already tried this but somehow I couldn't make it work smoothly. It might be related to something like internal zero padding or something that rnnoise is doing. I will try again for sure.

**Comment by lucianodato** [comment]
The parameter is there now. However there is some additional delay that I have to compensate or something related to phase or something that rnnoise filters are doing that when mixing wet and dry signal it sounds doubled. Will look further in the next weeks.

**Comment by lucianodato** [comment]
Done
