### ISSUE TITLE
meson.build failing with mesion version 0.47.0

### ISSUE THREAD

**Issue by CrocoDuckoDucks** [lucianodato/speech-denoiser#9]
Hi there!
When using the latest version from Arch repos (0.47.0) meson cannot build the software:

```
meson.build:13:0: ERROR:  C library 'rnnoise' not found

A full log can be found at /home/crocoduck/abs/.BuildTests/speech-denoiser-git/src/speech-denoiser/build/meson-logs/meson-log.txt
==> ERROR: A failure occurred in build().
    Aborting...
```
However, it does build just fine when using meson 0.46.1, which is the latest one cached by pacman on my system. I attached the meson-log.txt file.

It could be very well a problem in the Arch Linux meson package, but to make sure I must ask whether you are observing the same. The other option is that meson 0.47.0 has some change that break your meson.build file, or some bug. [This is the issue](https://github.com/mesonbuild/meson/issues/1936) that inspired me to downgrade meson.

Hope it helps!

[meson-log.txt](https://github.com/lucianodato/speech-denoiser/files/2173910/meson-log.txt)

**Comment by CrocoDuckoDucks** [comment]
It builds just fine with meson 0.47.1. It must have been a bug in meson.

**Comment by lucianodato** [comment]
@CrocoDuckoDucks great!
